### ISSUE TITLE
Custom Peer Entries Not Imported to c-Bridge

### ISSUE THREAD

**Issue by W4JEW** [wdatkinson/cBridge-Peer-Radio-ID-Update#1]
I am hoping you can help me - I've downloaded and installed your script. It's working very nicely with one exception.

If I make any entries in the custom_peers.csv file, they are successfully merged into the cbridge_peers.csv but they are never imported into the c-Bridge.

The examples that you have in the custom_peers.csv file are imported successfully, but nothing I add gets imported.

I was just curious to see if you have any ideas.

**Comment by nf9k** [comment]
Sounds like a formatting issue or perhaps some hidden characters.  What are you using as a text editor?  Can you upload your modified custom_peers.csv?

**Comment by W4JEW** [comment]
Thanks for getting back to me! Yes - that's what I was thinking as well. The funny thing is I even manually added the entries to the c-Bridge via the web interface, exported them to CSV, then tried using that to import and my entries still failed. Yours work every time.

Here's my custom_peers.csv

[custom_peers.csv](https://github.com/wdatkinson/cBridge-Peer-Radio-ID-Update/files/7034623/custom_peers.csv)
